// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("58cce921-676b-4b7d-a700-cfed0b2a9e35"),
                            Age = 25,
                            Email = "hr.01@myCompany.com",
                            Firstname = "Vinnie",
                            Lastname = "Cherry",
                            Password = "@password01",
                            Position = 0
                        },
                        new
                        {
                            Id = new Guid("b43193fb-81cd-4f64-85b3-880dd371cea3"),
                            Email = "hr.02@myCompany.com",
                            Firstname = "Rose",
                            Lastname = "Gonzales",
                            Password = "@password02",
                            Position = 0
                        },
                        new
                        {
                            Id = new Guid("3c797159-3414-4ba1-b48a-d9bbeac022d5"),
                            Age = 45,
                            Email = "hr.03@myCompany.com",
                            Firstname = "Montgomery",
                            Lastname = "Garcia",
                            Password = "@password03",
                            Position = 0
                        },
                        new
                        {
                            Id = new Guid("6f9d186f-7833-4dc8-87cc-3e5cfe080081"),
                            Age = 32,
                            Email = "manager.01@myCompany.com",
                            Firstname = "Max",
                            Lastname = "Rush",
                            Password = "@password04",
                            Position = 1
                        },
                        new
                        {
                            Id = new Guid("fc07af7a-261b-463f-b40e-e69413923ab4"),
                            Age = 44,
                            Email = "manager.02@myCompany.com",
                            Firstname = "Zohaib",
                            Lastname = "Wright",
                            Password = "@password05",
                            Position = 1
                        },
                        new
                        {
                            Id = new Guid("16cab7ab-cc60-469f-af19-9606cf772335"),
                            Age = 27,
                            Email = "developer.01@myCompany.com",
                            Firstname = "Harun",
                            Lastname = "Clayton",
                            Password = "@password06",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("9dc474d3-b9ab-4f78-86f4-0a4cf4811733"),
                            Age = 33,
                            Email = "developer.02@myCompany.com",
                            Firstname = "Glenn",
                            Lastname = "Carrillo",
                            Password = "@password07",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("1dc79443-1c1d-449f-867f-c33393980d20"),
                            Email = "developer.03@myCompany.com",
                            Firstname = "Rebekah",
                            Lastname = "Matthams",
                            Password = "@password08",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("c87b72e3-48e0-44d8-bbb1-d583053e27b5"),
                            Age = 51,
                            Email = "developer.04@myCompany.com",
                            Firstname = "Simeon",
                            Lastname = "Ferrell",
                            Password = "@password09",
                            Position = 2
                        },
                        new
                        {
                            Id = new Guid("4b5e77fc-1a65-4742-9a81-7e8fe4c0ec6f"),
                            Email = "developer.05@myCompany.com",
                            Firstname = "Jordan",
                            Lastname = "Mcpherson",
                            Password = "@password10",
                            Position = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
